---
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_MESSAGE =~ /^chore\(release\)/
      when: never
    - when: always

default:
  image: ubuntu:latest
  before_script:
    - TZ="Europe/Prague"
    - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

variables:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  GL_TF_BE: https://gitlab.com/api/v4/projects/31099306/terraform/state
  TF_HTTP_PASSWORD: $CI_JOB_TOKEN

stages:
  - validate
  - deploy
  - config
  - destroy
  - release

lint:
  stage: validate
  script:
    - apt-get update && apt-get upgrade -y
    - apt-get install --no-install-recommends -y ca-certificates curl git gnupg golang nodejs npm python3-pip shellcheck software-properties-common unzip
    - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
    - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    - apt-get update && apt-get install --no-install-recommends terraform
    - pip3 install checkov gitlint pre-commit yamllint
    - curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
    - gitlint
    - tools/check-sanity
    - npm install -g markdownlint-cli
    - GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt@v3.3.1
    - PATH="$PATH:/root/go/bin"
    - GITLAB_PRIVATE_TOKEN="$GL_TOKEN" pre-commit run --all-files
  interruptible: true
  rules:
    - when: always

deploy-prod:
  stage: deploy
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - /usr/bin/env
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  script:
    - echo "Deploy **$CI_ENVIRONMENT_NAME** environment \`$CI_ENVIRONMENT_SLUG\` (tier $CI_ENVIRONMENT_TIER) to <$CI_ENVIRONMENT_URL>"
    - terraform init -reconfigure -backend-config="address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG" -backend-config="lock_address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG/lock" -backend-config="unlock_address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG/lock"
    - terraform apply -auto-approve -var="ENV_SLUG=$CI_ENVIRONMENT_SLUG" -var="ENV_TIER=$CI_ENVIRONMENT_TIER"
    - PROD_IP=$(terraform output -raw hcloud_server_test_ipv4_address || echo "")
    - echo "PROD_IP=$PROD_IP" >> prod.env
  artifacts:
    reports:
      dotenv: prod.env
  environment:
    name: Production
    url: https://example.com
  rules:
    - if: $CI_COMMIT_TAG =~ /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
  resource_group: production

config-prod:
  stage: config
  image: gableroux/ansible:latest
  script:
    - echo "PROD_IP=$PROD_IP"
    - |
      if [ -n "$PROD_IP" ]; then
        echo "Configure **$CI_ENVIRONMENT_NAME** environment \`$CI_ENVIRONMENT_SLUG\` (tier $CI_ENVIRONMENT_TIER) to <$CI_ENVIRONMENT_URL>"
        eval $(ssh-agent -s)
        echo "$GL_CI_SSH_KEY" | tr -d '\r' | ssh-add -
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan "$PROD_IP" >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        ansible -u gitlab-ci -i "$PROD_IP," all -m ansible.builtin.ping
        ansible-playbook -u gitlab-ci -i "$PROD_IP," playbook.yml
      fi
  environment:
    name: Production
  needs:
    - deploy-prod
  rules:
    - if: $CI_COMMIT_TAG =~ /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
  resource_group: production

deploy-stag:
  stage: deploy
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - /usr/bin/env
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  script:
    - echo "Deploy **$CI_ENVIRONMENT_NAME** environment \`$CI_ENVIRONMENT_SLUG\` (tier $CI_ENVIRONMENT_TIER) to <$CI_ENVIRONMENT_URL>"
    - terraform init -reconfigure -backend-config="address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG" -backend-config="lock_address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG/lock" -backend-config="unlock_address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG/lock"
    - terraform apply -auto-approve -var="ENV_SLUG=$CI_ENVIRONMENT_SLUG" -var="ENV_TIER=$CI_ENVIRONMENT_TIER"
    - STAG_IP=$(terraform output -raw hcloud_server_test_ipv4_address || echo "")
    - echo "STAG_IP=$STAG_IP" >> stag.env
  artifacts:
    reports:
      dotenv: stag.env
  environment:
    name: Staging
    url: https://$CI_ENVIRONMENT_SLUG.example.com
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  resource_group: staging

config-stag:
  stage: config
  image: gableroux/ansible:latest
  script:
    - echo "STAG_IP=$STAG_IP"
    - |
      if [ -n "$STAG_IP" ]; then
        echo "Configure **$CI_ENVIRONMENT_NAME** environment \`$CI_ENVIRONMENT_SLUG\` (tier $CI_ENVIRONMENT_TIER) to <$CI_ENVIRONMENT_URL>"
        eval $(ssh-agent -s)
        echo "$GL_CI_SSH_KEY" | tr -d '\r' | ssh-add -
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan "$STAG_IP" >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        ansible -u gitlab-ci -i "$STAG_IP," all -m ansible.builtin.ping
        ansible-playbook -u gitlab-ci -i "$STAG_IP," playbook.yml
      fi
  environment:
    name: Staging
  needs:
    - deploy-stag
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  resource_group: staging

deploy-test:
  stage: deploy
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - /usr/bin/env
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  script:
    - echo "Deploy **$CI_ENVIRONMENT_NAME** environment \`$CI_ENVIRONMENT_SLUG\` (tier $CI_ENVIRONMENT_TIER) to <$CI_ENVIRONMENT_URL>"
    - terraform init -reconfigure -backend-config="address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG" -backend-config="lock_address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG/lock" -backend-config="unlock_address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG/lock"
    - terraform apply -auto-approve -var="ENV_SLUG=$CI_ENVIRONMENT_SLUG" -var="ENV_TIER=$CI_ENVIRONMENT_TIER"
    - TEST_IP=$(terraform output -raw hcloud_server_test_ipv4_address)
    - echo "TEST_IP=$TEST_IP" >> test.env
  artifacts:
    reports:
      dotenv: test.env
  environment:
    name: Testing/$CI_COMMIT_REF_SLUG
    url: https://$CI_ENVIRONMENT_SLUG.example.com
    on_stop: destroy-test
    auto_stop_in: 1 week
  rules:
    - if: $CI_COMMIT_TAG =~ /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
  resource_group: testing/$CI_COMMIT_REF_SLUG

config-test:
  stage: config
  image: gableroux/ansible:latest
  script:
    - echo "TEST_IP=$TEST_IP"
    - echo "Configure **$CI_ENVIRONMENT_NAME** environment \`$CI_ENVIRONMENT_SLUG\` (tier $CI_ENVIRONMENT_TIER) to <$CI_ENVIRONMENT_URL>"
    - eval $(ssh-agent -s)
    - echo "$GL_CI_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan "$TEST_IP" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ansible -u gitlab-ci -i "$TEST_IP," all -m ansible.builtin.ping
    - ansible-playbook -u gitlab-ci -i "$TEST_IP," playbook.yml
  environment:
    name: Testing/$CI_COMMIT_REF_SLUG
  needs:
    - deploy-test
  rules:
    - if: $CI_COMMIT_TAG =~ /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
  resource_group: testing/$CI_COMMIT_REF_SLUG

destroy-test:
  stage: destroy
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - /usr/bin/env
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  script:
    - echo "Destroy **$CI_ENVIRONMENT_NAME** environment \`$CI_ENVIRONMENT_SLUG\` (tier $CI_ENVIRONMENT_TIER) to <$CI_ENVIRONMENT_URL>"
    - terraform init -reconfigure -backend-config="address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG" -backend-config="lock_address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG/lock" -backend-config="unlock_address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG/lock"
    - terraform destroy -auto-approve -var="ENV_SLUG=$CI_ENVIRONMENT_SLUG" -var="ENV_TIER=$CI_ENVIRONMENT_TIER"
  environment:
    name: Testing/$CI_COMMIT_REF_SLUG
    action: stop
  needs:
    - deploy-test
  rules:
    - if: $CI_COMMIT_TAG =~ /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      when: manual
      allow_failure: true

deploy-dev:
  stage: deploy
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - /usr/bin/env
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  before_script:
    - apk update
    - apk add bash curl
  script:
    - tools/dev-env >> dev.env
    - . dev.env
    - |
      if [[ $DEV_ENV == "true" ]]; then
        echo "Deploy **$CI_ENVIRONMENT_NAME** environment \`$CI_ENVIRONMENT_SLUG\` (tier $CI_ENVIRONMENT_TIER) to <$CI_ENVIRONMENT_URL>"
        terraform init -reconfigure -backend-config="address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG" -backend-config="lock_address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG/lock" -backend-config="unlock_address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG/lock"
        terraform apply -auto-approve -var="ENV_SLUG=$CI_ENVIRONMENT_SLUG" -var="ENV_TIER=$CI_ENVIRONMENT_TIER"
        DEV_IP=$(terraform output -raw hcloud_server_test_ipv4_address)
        echo "DEV_IP=$DEV_IP" >> dev.env
      fi
  artifacts:
    reports:
      dotenv: dev.env
  environment:
    name: Development/$CI_COMMIT_REF_SLUG
    url: https://$CI_ENVIRONMENT_SLUG.example.com
    on_stop: destroy-dev
    auto_stop_in: 1 day
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "main"
  resource_group: development/$CI_COMMIT_REF_SLUG

config-dev:
  stage: config
  image: gableroux/ansible:latest
  script:
    - echo "DEV_ENV=$DEV_ENV"
    - echo "DEV_IP=$DEV_IP"
    - |
      if [[ $DEV_ENV == "true" ]]; then
        echo "Configure **$CI_ENVIRONMENT_NAME** environment \`$CI_ENVIRONMENT_SLUG\` (tier $CI_ENVIRONMENT_TIER) to <$CI_ENVIRONMENT_URL>"
        eval $(ssh-agent -s)
        echo "$GL_CI_SSH_KEY" | tr -d '\r' | ssh-add -
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan "$DEV_IP" >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        ansible -u gitlab-ci -i "$DEV_IP," all -m ansible.builtin.ping
        ansible-playbook -u gitlab-ci -i "$DEV_IP," playbook.yml
      fi
  environment:
    name: Development/$CI_COMMIT_REF_SLUG
  needs:
    - deploy-dev
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "main"
  resource_group: development/$CI_COMMIT_REF_SLUG

destroy-dev:
  stage: destroy
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - /usr/bin/env
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  script:
    - echo "DEV_ENV=$DEV_ENV"
    - |
      if [[ $DEV_ENV == "true" ]]; then
        echo "Destroy **$CI_ENVIRONMENT_NAME** environment \`$CI_ENVIRONMENT_SLUG\` (tier $CI_ENVIRONMENT_TIER) to <$CI_ENVIRONMENT_URL>"
        terraform init -reconfigure -backend-config="address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG" -backend-config="lock_address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG/lock" -backend-config="unlock_address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG/lock"
        terraform destroy -auto-approve -var="ENV_SLUG=$CI_ENVIRONMENT_SLUG" -var="ENV_TIER=$CI_ENVIRONMENT_TIER"
      fi
  environment:
    name: Development/$CI_COMMIT_REF_SLUG
    action: stop
  needs:
    - deploy-dev
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "main"
      when: manual
      allow_failure: true

release:
  stage: release
  script:
    - apt-get update && apt-get upgrade -y
    - apt-get install --no-install-recommends -y curl git npm
    - curl -sL https://deb.nodesource.com/setup_14.x -o setup_14.sh
    - bash ./setup_14.sh
    - apt-get install --no-install-recommends -y nodejs
    - npm install -g semantic-release @semantic-release/gitlab @semantic-release/github @semantic-release/git @semantic-release/changelog
    - npx semantic-release
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  resource_group: release
