---
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_MESSAGE =~ /^chore\(release\)/
      when: never
    - when: always

stages:
  - validate
  - deploy
  - config
  - destroy
  - release

default:
  image: alpine:latest
  before_script: &default_before_script
    - apk -U upgrade

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  GL_TF_BE: https://gitlab.com/api/v4/projects/31099306/terraform/state
  TF_HTTP_PASSWORD: $CI_JOB_TOKEN

lint:
  stage: validate
  variables:
    PRE_COMMIT_HOME: $CI_PROJECT_DIR/.cache/pre-commit
  before_script:
    - *default_before_script
    - apk add bash curl git go grep libffi-dev npm py-pip python3-dev shellcheck shfmt terraform unzip
    - pip install checkov pre-commit
    - npm install -g markdownlint-cli
    - curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
  script:
    - |
      if [ -z "${GL_TOKEN:-}" ]; then
          SKIP=gitlab-ci-linter pre-commit run -a --hook-stage manual
      else
          GITLAB_PRIVATE_TOKEN="$GL_TOKEN" pre-commit run -a --hook-stage manual
      fi
  cache:
    paths:
      - $PRE_COMMIT_HOME
    when: always
  interruptible: true
  rules:
    - when: always

.test:
  stage: validate
  before_script:
    - *default_before_script
    - apk add bats
  script:
    - scripts/test full

test-full:
  extends: .test
  interruptible: true
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"

test-nightly:
  extends: .test
  script:
    - scripts/test nightly
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

.deploy-env:
  stage: deploy
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - /usr/bin/env
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  script:
    - echo "Deploy **$CI_ENVIRONMENT_NAME** environment \`$CI_ENVIRONMENT_SLUG\` (tier $CI_ENVIRONMENT_TIER) to <$CI_ENVIRONMENT_URL>"
    - terraform init -reconfigure -backend-config="address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG" -backend-config="lock_address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG/lock" -backend-config="unlock_address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG/lock"
    - terraform apply -auto-approve -var="ENV_SLUG=$CI_ENVIRONMENT_SLUG" -var="ENV_TIER=$CI_ENVIRONMENT_TIER"
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .terraform

.config-env:
  stage: config
  image: gableroux/ansible:latest
  before_script:
    - *default_before_script
    - apk add jq
    - pip install hcloud
  script:
    - echo "Configure **$CI_ENVIRONMENT_NAME** environment \`$CI_ENVIRONMENT_SLUG\` (tier $CI_ENVIRONMENT_TIER) to <$CI_ENVIRONMENT_URL>"
    - sed -i "s/env-slug/$CI_ENVIRONMENT_SLUG/" hcloud.yml
    - SSH_HOST_LIST=$(ansible-inventory -i hcloud.yml --list | jq -r '._meta.hostvars | with_entries(.value |= .ipv4) | join(",")')
    - |
      if [ -n "$SSH_HOST_LIST" ]; then
        echo "Configure IPs: $SSH_HOST_LIST"
        eval $(ssh-agent -s)
        echo "$GL_CI_SSH_KEY" | tr -d '\r' | ssh-add -
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan "$SSH_HOST_LIST" >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        ansible -u gitlab-ci -i hcloud.yml env -m ansible.builtin.ping
        ansible-playbook -u gitlab-ci -i hcloud.yml playbook.yml
      fi

.destroy-env:
  stage: destroy
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - /usr/bin/env
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  variables:
    GIT_STRATEGY: none
  before_script:
    - *default_before_script
    - apk add git
  script:
    - echo "Destroy **$CI_ENVIRONMENT_NAME** environment \`$CI_ENVIRONMENT_SLUG\` (tier $CI_ENVIRONMENT_TIER) to <$CI_ENVIRONMENT_URL>"
    - |
      if [ ! -d .git ]; then
        git init -b main
        git remote add origin $CI_REPOSITORY_URL
        git fetch origin $CI_COMMIT_SHA --depth=1
        git reset --hard FETCH_HEAD
      fi
    - terraform init -reconfigure -backend-config="address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG" -backend-config="lock_address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG/lock" -backend-config="unlock_address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG/lock"
    - terraform destroy -auto-approve -var="ENV_SLUG=$CI_ENVIRONMENT_SLUG" -var="ENV_TIER=$CI_ENVIRONMENT_TIER"
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .terraform

.env-prod:
  environment:
    name: Production
    url: https://example.com
  rules:
    - if: $CI_COMMIT_TAG =~ /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
  resource_group: production

.env-stag:
  environment:
    name: Staging
    url: https://$CI_ENVIRONMENT_SLUG.example.com
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "schedule"
  resource_group: staging

.env-test:
  environment:
    name: Testing/$CI_COMMIT_REF_SLUG
    url: https://$CI_ENVIRONMENT_SLUG.example.com
  rules:
    - if: $CI_COMMIT_TAG =~ /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
  resource_group: testing/$CI_COMMIT_REF_SLUG

.env-dev:
  before_script:
    - *default_before_script
    - apk add bash curl
  environment:
    name: Development/$CI_COMMIT_REF_SLUG
    url: https://$CI_ENVIRONMENT_SLUG.example.com
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "main"
  resource_group: development/$CI_COMMIT_REF_SLUG

deploy-prod:
  extends: [.deploy-env, .env-prod]

config-prod:
  extends: [.config-env, .env-prod]
  needs:
    - deploy-prod

deploy-stag:
  extends: [.deploy-env, .env-stag]

config-stag:
  extends: [.config-env, .env-stag]
  needs:
    - deploy-stag

deploy-test:
  extends: [.deploy-env, .env-test]
  environment:
    on_stop: destroy-test
    auto_stop_in: 1 week

config-test:
  extends: [.config-env, .env-test]
  environment:
    name: Testing/$CI_COMMIT_REF_SLUG
  needs:
    - deploy-test

destroy-test:
  extends: [.destroy-env, .env-test]
  environment:
    action: stop
  needs:
    - deploy-test
  rules:
    - if: $CI_COMMIT_TAG =~ /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      when: manual

deploy-dev:
  extends: [.deploy-env, .env-dev]
  script:
    - |
      if scripts/dev-env; then
        echo "Deploy **$CI_ENVIRONMENT_NAME** environment \`$CI_ENVIRONMENT_SLUG\` (tier $CI_ENVIRONMENT_TIER) to <$CI_ENVIRONMENT_URL>"
        terraform init -reconfigure -backend-config="address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG" -backend-config="lock_address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG/lock" -backend-config="unlock_address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG/lock"
        terraform apply -auto-approve -var="ENV_SLUG=$CI_ENVIRONMENT_SLUG" -var="ENV_TIER=$CI_ENVIRONMENT_TIER"
      fi
  environment:
    on_stop: destroy-dev
    auto_stop_in: 1 day

config-dev:
  extends: [.config-env, .env-dev]
  before_script:
    - *default_before_script
    - apk add bash curl jq
    - pip install hcloud
  script:
    - |
      if scripts/dev-env; then
        echo "Configure **$CI_ENVIRONMENT_NAME** environment \`$CI_ENVIRONMENT_SLUG\` (tier $CI_ENVIRONMENT_TIER) to <$CI_ENVIRONMENT_URL>"
        sed -i "s/env-slug/$CI_ENVIRONMENT_SLUG/" hcloud.yml
        SSH_HOST_LIST=$(ansible-inventory -i hcloud.yml --list | jq -r '._meta.hostvars | with_entries(.value |= .ipv4) | join(",")')
        if [ -n "$SSH_HOST_LIST" ]; then
          echo "Configure IPs: $SSH_HOST_LIST"
          eval $(ssh-agent -s)
          echo "$GL_CI_SSH_KEY" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan "$SSH_HOST_LIST" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          ansible -u gitlab-ci -i hcloud.yml env -m ansible.builtin.ping
          ansible-playbook -u gitlab-ci -i hcloud.yml playbook.yml
        fi
      fi
  needs:
    - deploy-dev

destroy-dev:
  extends: [.destroy-env, .env-dev]
  before_script:
    - *default_before_script
    - apk add bash curl git
  script:
    - |
      if scripts/dev-env; then
        echo "Destroy **$CI_ENVIRONMENT_NAME** environment \`$CI_ENVIRONMENT_SLUG\` (tier $CI_ENVIRONMENT_TIER) to <$CI_ENVIRONMENT_URL>"
        if [ ! -d .git ]; then
          git init -b main
          git remote add origin $CI_REPOSITORY_URL
          git fetch origin $CI_COMMIT_SHA --depth=1
          git reset --hard FETCH_HEAD
        fi
        terraform init -reconfigure -backend-config="address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG" -backend-config="lock_address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG/lock" -backend-config="unlock_address=$GL_TF_BE/$CI_ENVIRONMENT_SLUG/lock"
        terraform destroy -auto-approve -var="ENV_SLUG=$CI_ENVIRONMENT_SLUG" -var="ENV_TIER=$CI_ENVIRONMENT_TIER"
      fi
  environment:
    action: stop
  needs:
    - deploy-dev
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "main"
      when: manual
      allow_failure: true

release:
  stage: release
  image:
    name: node:alpine
    entrypoint: [""]
  before_script:
    - *default_before_script
    - apk add git
    - npm install -g semantic-release @semantic-release/gitlab @semantic-release/git @semantic-release/changelog
  script:
    - npx semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(((0|[1-9]\d*)\.)(((0|[1-9]\d*|x)\.)?x)|main|next(-major)?|beta|alpha)$/ && $CI_PIPELINE_SOURCE != "schedule"
  resource_group: release
