---
default:
  image: ubuntu:latest
  before_script:
    - TZ="Europe/Prague"
    - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

variables:
  TF_IN_AUTOMATION: "true"
  GL_TF_BE: https://gitlab.com/api/v4/projects/31099306/terraform/state
  TF_HTTP_PASSWORD: $CI_JOB_TOKEN

stages:
  - validate
  - deploy
  - release

lint:
  stage: validate
  script:
    - apt-get update && apt-get upgrade -y
    - apt-get install --no-install-recommends -y ca-certificates curl git golang nodejs npm python3-pip shellcheck software-properties-common unzip
    - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
    - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    - apt-get update && apt-get install --no-install-recommends terraform
    - pip3 install checkov gitlint pre-commit yamllint
    - curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
    - gitlint
    - tools/check-sanity
    - npm install -g markdownlint-cli
    - GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt@v3.3.1
    - PATH="$PATH:/root/go/bin"
    - GITLAB_PRIVATE_TOKEN="$GL_TOKEN" pre-commit run --all-files

deploy-prod:
  stage: deploy
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - /usr/bin/env
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  variables:
    TF_TARGET_ENV_NAME: Production
    TF_TARGET_ENV_SLUG: prod
  script:
    - echo "Deploy **$TF_TARGET_ENV_NAME** environment \`$TF_TARGET_ENV_SLUG\` to <https://example.com>"
    - terraform init -reconfigure -backend-config="address=$GL_TF_BE/$TF_TARGET_ENV_SLUG" -backend-config="lock_address=$GL_TF_BE/$TF_TARGET_ENV_SLUG/lock" -backend-config="unlock_address=$GL_TF_BE/$TF_TARGET_ENV_SLUG/lock" -input=false
    - terraform apply -auto-approve -input=false
  rules:
    - if: $CI_COMMIT_TAG =~ /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

deploy-stag:
  stage: deploy
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - /usr/bin/env
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  variables:
    TF_TARGET_ENV_NAME: Staging
    TF_TARGET_ENV_SLUG: stag
  script:
    - echo "Deploy **$TF_TARGET_ENV_NAME** environment \`$TF_TARGET_ENV_SLUG\` to <https://$TF_TARGET_ENV_SLUG.example.com>"
    - terraform init -reconfigure -backend-config="address=$GL_TF_BE/$TF_TARGET_ENV_SLUG" -backend-config="lock_address=$GL_TF_BE/$TF_TARGET_ENV_SLUG/lock" -backend-config="unlock_address=$GL_TF_BE/$TF_TARGET_ENV_SLUG/lock" -input=false
    - terraform apply -auto-approve -input=false
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

deploy-test:
  stage: deploy
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - /usr/bin/env
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  variables:
    TF_TARGET_ENV_NAME: Testing/$CI_COMMIT_REF_SLUG
    TF_TARGET_ENV_SLUG: test-$CI_ENVIRONMENT_SLUG
  script:
    - echo "Deploy **$TF_TARGET_ENV_NAME** environment \`$TF_TARGET_ENV_SLUG\` to <https://$TF_TARGET_ENV_SLUG.example.com>"
    - terraform init -reconfigure -backend-config="address=$GL_TF_BE/$TF_TARGET_ENV_SLUG" -backend-config="lock_address=$GL_TF_BE/$TF_TARGET_ENV_SLUG/lock" -backend-config="unlock_address=$GL_TF_BE/$TF_TARGET_ENV_SLUG/lock" -input=false
    - terraform apply -auto-approve -input=false
  rules:
    - if: $CI_COMMIT_TAG =~ /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

deploy-dev:
  stage: deploy
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - /usr/bin/env
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  variables:
    TF_TARGET_ENV_NAME: Development/$CI_COMMIT_REF_SLUG
    TF_TARGET_ENV_SLUG: dev-$CI_ENVIRONMENT_SLUG
  script:
    - echo "Deploy **$TF_TARGET_ENV_NAME** environment \`$TF_TARGET_ENV_SLUG\` to <https://$TF_TARGET_ENV_SLUG.example.com>"
    - terraform init -reconfigure -backend-config="address=$GL_TF_BE/$TF_TARGET_ENV_SLUG" -backend-config="lock_address=$GL_TF_BE/$TF_TARGET_ENV_SLUG/lock" -backend-config="unlock_address=$GL_TF_BE/$TF_TARGET_ENV_SLUG/lock" -input=false
    - terraform apply -auto-approve -input=false
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "main"

release:
  stage: release
  script:
    - apt-get update
    - apt-get upgrade -y
    - apt-get install --no-install-recommends -y curl git npm
    - curl -sL https://deb.nodesource.com/setup_14.x -o setup_14.sh
    - bash ./setup_14.sh
    - apt-get install --no-install-recommends -y nodejs
    - npm install -g semantic-release @semantic-release/gitlab @semantic-release/github @semantic-release/git @semantic-release/changelog
    - npx semantic-release
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
