---
# cSpell:ignore pygrep
default_stages: [commit, manual, merge-commit, push]
repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.0dev
    hooks:
      - id: gitlint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: .*\.drawio$
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: no-commit-to-branch
      - id: trailing-whitespace
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: check-mailmap
      - id: forbid-binary
        exclude: .*\.png$
      - id: git-check
      - id: git-dirty
      - id: script-must-have-extension
        exclude: .*\.bats$
      - id: script-must-not-have-extension
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        args: [--strict]
  - repo: https://gitlab.com/devopshq/gitlab-ci-linter
    rev: v1.0.3
    hooks:
      - id: gitlab-ci-linter
  - repo: local
    hooks:
      - id: anti-todo
        name: anti-todo
        entry: (?i)#\s*\b(wip|todo|tbd)\b
        language: pygrep
        types: [text]
        stages: [push, manual]
      - id: shfmt
        name: shfmt
        entry: shfmt -i 4
        language: system
        types: [shell]
      - id: shfmt-bats
        name: shfmt-bats
        entry: shfmt -ln bats -i 4
        language: system
        files: .*\.bats$
      - id: shellcheck
        name: shellcheck
        entry: shellcheck -x -P scripts:scripts/shellib
        language: system
        types: [shell]
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.15.3
    hooks:
      - id: gitleaks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.1
    hooks:
      - id: terraform_fmt
        args:
          - --args=-diff
          - --args=-write=false
      - id: terraform_validate
      - id: terraform_tflint
        args:
          - --args=--enable-rule=terraform_documented_variables
      - id: terraform_checkov
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.16.0
    hooks:
      - id: terraform-docs-go
        args: [./terraform]
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v6.12.1
    hooks:
      - id: ansible-lint
        args: [-c, .ansible-lint.yml]
