---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: no-commit-to-branch
      - id: trailing-whitespace
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: forbid-binary
      - id: script-must-have-extension
      - id: script-must-not-have-extension
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.29.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: [--strict]
  - repo: https://gitlab.com/devopshq/gitlab-ci-linter
    rev: v1.0.4
    hooks:
      - id: gitlab-ci-linter
  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        entry: shfmt -i 4
        language: system
        types: [shell]
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.56.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-diff
          - --args=-write=false
      - id: terraform_validate
      - id: terraform_tflint
        args:
          - --args=--enable-rule=terraform_documented_variables
      - id: checkov
