---
extends: default

rules:
  braces:
    min-spaces-inside: 1
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
    ignore: |
      cloud-config.yml
  document-start:
    ignore: |
      cloud-config.yml
  empty-lines:
    max: 1
  empty-values: enable
  indentation:
    spaces: 2
  line-length: disable
  octal-values: enable
  quoted-strings:
    required: only-when-needed
