#cloud-config  # yamllint disable-line rule:comments,document-start
users:
  - default
  - name: gitlab-ci
    gecos: GitLab CI/CD
    primary_group: users
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvjLHEObA3CSaxnOVvRH55t0VovwMARBAbwsyvy9w0cCX5CifW9u7xNKRpQfzQMKDRl1uQWzAdnk7HHPeW810Rc/j9dWJFd3gCa2aptzU7pzYG5nSyyvlYQF2SsILbg8xyK+W+e/Qb6ILgSeIoD+sJf2uP5+Umy4g9e4tOJYwfiM/XySDRL+925FfmtzpPJwauLJALFq9uERUDLugA52s44vkZBYRTf6gCfbyom/FLO8qvHq6+lHLGrPgbIYO/pf+/ftwG+oB/qw/9tFvJboYTKSE/91WWzLIj5C+0ghe+GCugxpQ5fMawf4zKrqfDcQRcLgN5KSHnEd6YP0ZbiYfftUIH1JeJId5EiXnSs62/iOiYGF4pZr6BIkB+N2WLWS6OS4aRaxWFu2QVMot2uBKbQ8WUStSb/GJJst/lEvPgRKW0DxtG1RY6TkBzGzGTiOczSKwHxH7IvhVYq4UKvlLtTD5zDnjJGe8c9i5vBo5+NLxcEYEQPKmd4sJPrzw8mMU= ci-cd@gitlab.com # yamllint disable-line rule:line-length
  - name: mb
    gecos: Martin Bruzina
    primary_group: users
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDNPlbQkcPrwETsk43w+HNLXEz9CA+qDgRXbK7rkAgaJEu6IlK+PKssrl8Tj7TU+1Qfcnn5ng1WN+oK+JJkh41645jJrD9OMDMzvmDPunfTspGJNtQqBjXHHn4idM/MhHLWFuFnFWfs7PjJmFLySH/q075kMLS+F5GIfiSAaPC0tqi8ytlRoQjF7XHM2Lrml3ipVuAlz+1pmVismvG80u29rEiF18Ph+NcY/55oJSMHMnBhC7H2/rId3f2p7Cm1r5B8bSaeXpARp3sn9yAiD7N2MQRcaDqJ2PSM6R8TF6cCOGm2aOSZ/XQbhnWyWTxb+xeDxZxRrOBJOPdorRQ32GJh2/vDZDEcr2I1xHqtgzxYMKVzVyYhUbEOw+Fe/F8sPostQhFjclaUaZJk6Lh+4Y2esTOZpIs+EN8KyCsy+Yx5ROpO+xPbsQTeiSnlLJenfPFq8guvI7u/RJOsqP3LDyuShdyiDE5zw/9URnCHnuOg110eUw++KB6Lcm4EY+dQJPmpwoSgNRvcTKL9sY2rm9icw7FzXbguFLA9Mm1NCbX2CVTrL4iOajgVjGVOAtWVqKoI7RwUDlF5+mLudb2mQ08kVJ5OUkzqUewndlIMzQvI8XKuabOhqtiadUbKFvhJ3p8ljCR++ODgkjPmobmNrY5Nr7EFRYtsjkfqv7Sq5JUhZw== mb@pc0.xeb.is # yamllint disable-line rule:line-length
