#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
LANG=C

# shellcheck source=./shellib/shellib.sh
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/shellib/shellib.sh"

# Install dependencies
function install_dependencies() {
    apt_add "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" 'https://apt.releases.hashicorp.com/gpg'
    pkgs install 'apt:git' 'apt:python3-pip' 'pip:pre-commit' 'pip:gitlint' 'pip:codespell' 'snap:node' 'npm:markdownlint-cli' \
        'pip:yamllint' 'snap:shfmt' 'snap:shellcheck' 'apt:bats' \
        'apt:terraform' \
        'curl2bash:tflint=https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh' \
        'pip:checkov' 'snap:golang' 'apt:ansible' 'pip:ansible-lint' 'pip:hcloud'
    ansible-galaxy collection install ansible.posix
}

# Skip execution under test
if [ "${BASH_SOURCE[0]}" == "${0}" ]; then
    install_dependencies
fi
