#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
LANG=C

# shellcheck source=./shellib/shellib.sh
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/shellib/shellib.sh"

# Update repository pre-commit
function update_pre_commit {
    pre-commit autoupdate
    pre-commit gc
}

# Update repository submodules
function update_git_submodules() {
    git submodule update --remote --merge
}

# Update repository terraform
function update_terraform() {
    if [ -d 'terraform/.terraform' ] && [ -n "${TF_HTTP_PASSWORD:-}" ]; then
        pushd terraform
        terraform init -upgrade
        popd
    else
        notice 'Terraform is not initialized or TF_HTTP_PASSWORD variable is empty, Terraform updade skipped'
    fi
}

# Skip execution under test
if [ "${BASH_SOURCE[0]}" == "${0}" ]; then
    update_pre_commit
    update_git_submodules
    update_terraform
fi
