---
- name: Set up all machines
  hosts:
    - env # Use `env` instead of `all` or `hcloud`, see README.md#caveats
  roles:
    - xebis.ansible.system
    - xebis.ansible.firewall
    - xebis.ansible.fail2ban
    - xebis.ansible.iam
    - xebis.ansible.bash
    - xebis.ansible.starship
    - xebis.ansible.admin
    - role: lablabs.rke2
      become: true
