---
- name: Set up all machines
  hosts:
    - env # Use `env` instead of `all` or `hcloud`, see README.md#caveats
  roles:
    - xebis.ansible.system
    - xebis.ansible.firewall
    - common
    - security
    - access
