---
- name: Install fail2ban deb package
  become: true
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: Start service fail2ban
  become: true
  ansible.builtin.service:
    name: fail2ban
    enabled: true
    state: started
